Private event Project
Emmyn5600/PrivateEvent pull request #1
Opened 2021-05-05 15:57 UTC by Emmyn5600

### This pull request contains the following features:

* ### Update Readme file
* ### Created form for signup and sign in before creating or view an event
* ### User should create an event after signing or signing up 
* ### User should click attend the event button to attend the event
* ### user should cancel or ignore to attend the event

2021-05-05 16:59 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Emmyn5600 and @VanessaAoki  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of this project requirements so carefully, keep it up, and your project is really almost done.
:+1: I liked your User interface, it's really awesome.
:+1: Your readme file is also professional and it shows your potential of attention to details, keep up the good job guys :muscle: 
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming (covered by automated tests) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from Odin)
=> Currently you don't have a user's showpage link, that route is even missing from the routes of this project, kindly fix this issue. 
- [ ] Models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from Pathwright)
- [ ] Authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from Pathwright)
- [ ] Event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from Pathwright)
- [ ] There should be NO application logic in the views nor helpers (no Post.new, Comment.create, current_user.friends.find_by(...)...). Everything connected with data processing should be encapsulated in models and used in controllers. View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb). There shoud be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it.
=> To help you understand what to change here, is that you need to move all of if conditions statement, data manipulations, and loops from all of the `.html.erb` files and move those logic to `app/helpers/*_helper.rb` files 

# [Optional changes] :yellow_circle: 
- [ ] It would be very nice if you hide the new event button if the user is not signed in
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-05-05 16:59 UTC, descholar-ceo commented on db/migrate/20210503194732_create_events.rb
> +      t.integer :creator_id
- [ ] [required] Events table in migrations has creator_id as the foreign key ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from Odin)

2021-05-05 16:59 UTC, descholar-ceo commented on app/views/user/show.html.erb
> +<% end %>
- [ ] [Required] Kindly remove this logic from the views, you can always use helper methods for all of the view methods

2021-05-05 16:59 UTC, descholar-ceo commented on app/views/layouts/application.html.erb
> +              </p>
- [ ] [Required] Kindly remove this logic from the views, you can always use helper methods for all of the view methods

2021-05-06 16:47 UTC, ElijahTobs approved these changes
# Status: Approved! :tada: 

## Congratulations @Emmyn5600 and @VanessaAoki  

### Good job implementing the changes requested by the previous TSE.

## You can now merge and submit.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-05-06 16:54 UTC, merged